#### Lab 1: Recursive Function

In [1]:
# A recursive function to calculate factorial
def factorial(n):
    # Base condition
    if n == 0:
        return 1
    else:
        return n * factorial(n-1) # use of function within the function

# Calculating the factorial of 5
result = factorial(5)
print(result) # Output: 120

120

In [2]:
#Sum of digit by using recursive function
def digit(n):
    if n<10:
        return n
    else:
        return n%10+digit(n//10)

n=int(input('n='))
s=digit(n)
print(f'Sum of digit of {n}=',s)

n=120
Sum of digit of 120= 3

In [3]:
nums=[2,8,5,9,11,16,7]
max(nums)

16

In [4]:
#From a given list find the maximum and minimum number without using inbuilt function and use recursive function
def max_f(l):
    if len(l)==1:
        return l[0]
    else:
        return max(l[0],max_f(l[1:]))
nums=[2,8,5,9,11,16,7]
max_f(nums)

16

In [6]:
import math
math.pow(3,2) #3^2

9.0

In [7]:
#Power with recursive function n to the power k
def power(n,k):
    if k==0:
        return 1
    else:
        return n*power(n,k-1)
power(3,3)

27

In [9]:
s='BadriahPython'
len(s)

13

In [10]:
#Find the length of a string by using recursive function
def find_l(s):
    if s=='':
        return 0
    else:
        return 1 + find_l(s[1:])
s='Badriah'
find_l(s)

7

In [ ]:
#Calculate the arithmetic sum from 1 to n
def sum_till(n):
    if n==1:
        return 1
    else:
        return n+sum_till(n-1)
sum_till(5) # 1+2+3+4+5 = 15

15

In [ ]:
#Create a recursive Python function to find the nth Fibonacci number.
def find_fib(n):
    if n<=1:
        return 1
    else:
        return find_fib(n-1)+find_fib(n-2)
find_fib(6)

13

In [11]:
# Write a recursive function that will count a character will come how many times with in string
def count_c(s,c):
    if s=='':
        return 0
    elif s[0]==c:
        return 1+count_c(s[1:],c)
    else:
        return count_c(s[1:],c)
s='Badriah'
count_c(s,'a')

2

#### Lab 2: Pandas Library

In [ ]:
import pandas as pd
S = pd.Series([11, 28, 72, 3, 5, 8])
print(S)

0    11
1    28
2    72
3     3
4     5
5     8
dtype: int64

In [ ]:
print(S.index)
print(S.values)

RangeIndex(start=0, stop=6, step=1)
[11 28 72  3  5  8]

In [ ]:
fruits = ['apples', 'oranges', 'cherries', 'pears']
quantities = [20, 33, 52, 10]
S = pd. Series(quantities, index=fruits)
print(S)

apples      20
oranges     33
cherries    52
pears       10
dtype: int64

In [ ]:
fruits = ['apples', 'oranges', 'cherries', 'pears']
fruits1 = ['apples', 'oranges', 'cherries', 'raspberry']
S = pd.Series([20, 33, 52, 10], index=fruits)
S2 = pd.Series([17, 13, 31, 32], index=fruits1)
print(S + S2)
print("sum of S: ", sum(S))
print(S['apples'])

apples       37.0
cherries     83.0
oranges      46.0
pears         NaN
raspberry     NaN
dtype: float64
sum of S:  115
20

#### Lab 3: Creation  Dataset in Python

In [ ]:
import pandas as pd
data={
    'NAME':['A','B','C','D','E','F','G'],
    'AGE':[22,23,21,24,25,26,27],
    'GENDER':['M','F','M','M','F','F','M'],
    'MARKS':[78,70,83,85,89,82,91]
}
print(data)
#Convert into data frame
df=pd.DataFrame(data)
print(df)

{'NAME': ['A', 'B', 'C', 'D', 'E', 'F', 'G'], 'AGE': [22, 23, 21, 24, 25, 26, 27], 'GENDER': ['M', 'F', 'M', 'M', 'F', 'F', 'M'], 'MARKS': [78, 70, 83, 85, 89, 82, 91]}
  NAME  AGE GENDER  MARKS
0    A   22      M     78
1    B   23      F     70
2    C   21      M     83
3    D   24      M     85
4    E   25      F     89
5    F   26      F     82
6    G   27      M     91

#### Lab 4: Data Reshaping, Filtering, & Handle the Missing Values.

In [ ]:
#Import packages
import pandas as pd #for dataframes (like Excel)
import numpy as np #Numerical Operations

#Assign data
#data is a Dictionary of Lists
data = {'NAME':['A','B','C','D','E','F','G'],
        'AGE':[22,23,21,24,25,26,27],
        'GENDER':['M','F','M','M','F','F','M'],
        'MARKS':[78,70, np.nan ,85,89,82,np.nan]}
# np.nan indicates missing values

#Convert into DataFrame
df=pd.DataFrame(data)
#Display the Data
df

  NAME  AGE GENDER  MARKS
0    A   22      M   78.0
1    B   23      F   70.0
2    C   21      M    NaN
3    D   24      M   85.0
4    E   25      F   89.0
5    F   26      F   82.0
6    G   27      M    NaN

In [ ]:
#Categorize gender
df['GENDER']=df['GENDER'].map({'M':0,'F':1})
#Mapping means convert one set of values to another.
#'M' is mapped (converted) to 0 and 'F' is mapped to 1
df

  NAME  AGE  GENDER  MARKS
0    A   22       0   78.0
1    B   23       1   70.0
2    C   21       0    NaN
3    D   24       0   85.0
4    E   25       1   89.0
5    F   26       1   82.0
6    G   27       0    NaN

In [ ]:
#Shows the selected column as DataFrame (table)
df.filter(['NAME'])

  NAME
0    A
1    B
2    C
3    D
4    E
5    F
6    G

In [ ]:
#Shows the column as Series not table
df['NAME']

0    A
1    B
2    C
3    D
4    E
5    F
6    G
Name: NAME, dtype: object

In [ ]:
#Show age column from the DataFrame as values
df['AGE']

0    22
1    23
2    21
3    24
4    25
5    26
6    27
Name: AGE, dtype: int64

In [ ]:
#Shows boolean output, checks each row for the condition
df['AGE'] == 21

0    False
1    False
2     True
3    False
4    False
5    False
6    False
Name: AGE, dtype: bool

In [ ]:
#Shows the row where the condition is met
df[df['AGE'] <= 24]

  NAME  AGE  GENDER  MARKS
0    A   22       0   78.0
1    B   23       1   70.0
2    C   21       0    NaN
3    D   24       0   85.0

In [ ]:
#Check for missibng values (NaN) in DataFrame
df.isnull()

    NAME    AGE  GENDER  MARKS
0  False  False   False  False
1  False  False   False  False
2  False  False   False   True
3  False  False   False  False
4  False  False   False  False
5  False  False   False  False
6  False  False   False   True

In [ ]:
#To get count of missing (NaN) values per column
df.isnull().sum()

NAME      0
AGE       0
GENDER    0
MARKS     2
dtype: int64

In [ ]:
#Shows column with missing value as boolean
df.isnull().any()

NAME      False
AGE       False
GENDER    False
MARKS      True
dtype: bool

In [ ]:
# Calculate the mean
mean = df['MARKS'].mean()
print(mean)

80.8

In [ ]:
# Replace NaN values with mean
df['MARKS'].fillna(mean)
df['MARKS'].mean()
df.dropna() #Remove rows with any NaNs

  NAME  AGE  GENDER  MARKS
0    A   22       0   78.0
1    B   23       1   70.0
3    D   24       0   85.0
4    E   25       1   89.0
5    F   26       1   82.0