## Lab 1: Data Filtering

In [31]:
import pandas as pd
# Create a sample DataFrame
df = pd.DataFrame({'A': [1, 2, 3, 4], 'B': ['X', 'Y', 'Z', 'W']})
df

   A  B
0  1  X
1  2  Y
2  3  Z
3  4  W

### Boolean Indexing

In [34]:
#Boolean Indexing - Only the rows where the condition in TRUE.
#This works on row column 
# Filter rows where values in column 'A' are greater than 2
filtered_df = df[df['A'] > 2]
print(filtered_df)

   A  B
2  3  Z
3  4  W

### Query Method

In [3]:
#Using Query Method just like SQL
filtered_df = df.query('A > 2')
print(filtered_df)

   A  B
2  3  Z
3  4  W

In [4]:
filtered_df = df.query('A > 2 and B =="Z"')
print(filtered_df)

   A  B
2  3  Z

### Using loc and iloc

In [5]:
# loc - label based (column names)
# Select rows where column 'A' is greater than 2
# df.loc[row_condition, column_selection]
filtered_df = df.loc[df['A'] > 2, ['A','B']]
print(filtered_df)

   A  B
2  3  Z
3  4  W

In [6]:
# iloc - index based (row numbers)
# Show the first two rows
filtered_df = df.iloc[0:2]
print(filtered_df)

   A  B
0  1  X
1  2  Y

### Multiple Conditions

In [7]:
# Multiple Conditions - AND &, OR|, NOT~
# Filter rows where column 'A' is greater than 2 and column 'B' equals 'Z'
filtered_df = df[(df['A'] > 2) & ~(df['B'] == 'Z')]
print(filtered_df)

   A  B
3  4  W

### Reading Data from CSV

In [8]:
import os
os.getcwd() #Current Working Directory

'C:\\Users\\khans\\Downloads'

In [ ]:
os.chdir('Downloads') #Change location to Downloads

In [38]:
df=pd.read_csv('Iris.csv')
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [39]:
df.head(3) #Print only top 3 rows

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa

In [40]:
df.tail(3) #Print only last 3 rows

     sepal_length  sepal_width  petal_length  petal_width    species
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

### Viewing Columns

In [41]:
#Viewing Columns
df.columns #It will print all the columns as an index

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [42]:
list(df.columns) # It will print all column names as a list

['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']

In [43]:
# Select one column - Series
df['sepal_length']

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length, Length: 150, dtype: float64

In [44]:
#Any one column can be selected for print as series
type(df['sepal_length'])

pandas.core.series.Series

In [47]:
# df['sepal_length','species'] - Gives you error
type(df[['sepal_length','species']]) # Gives you multiple columns

pandas.core.frame.DataFrame

### Exploring the DataFrame

In [19]:
#To check the data types of the columns
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [20]:
#To know the full information about the data frame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [21]:
#To get the full description(mathematical and statistical) about the dataframe
#It will give you the maximum, minimum, STD, count, quartile value of int and float column
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

### Row Slicing

In [22]:
#To print some rows form the data frame with respect to column
df[['sepal_length']][4:11]

    sepal_length
4            5.0
5            5.4
6            4.6
7            5.0
8            4.4
9            4.9
10           5.4

In [23]:
#Print the rows with steps or jumps
df[['sepal_length','species']][1:21:2]

    sepal_length species
1            4.9  setosa
3            4.6  setosa
5            5.4  setosa
7            5.0  setosa
9            4.9  setosa
11           4.8  setosa
13           4.3  setosa
15           5.7  setosa
17           5.1  setosa
19           5.1  setosa

### Transposing a DataFrame

In [24]:
#Reverse Rows & Columns
a=df[['sepal_length','species']]
a.T #Here T stand for Transpose

,0,1,2,3,4,5,6,7,8,9,...,140,141,142,143,144,145,146,147,148,149
sepal_length,5.1,4.9,4.7,4.6,5,5.4,4.6,5,4.4,4.9,...,6.7,6.9,5.8,6.8,6.7,6.7,6.3,6.5,6.2,5.9
species,setosa,setosa,setosa,setosa,setosa,setosa,setosa,setosa,setosa,setosa,...,virginica,virginica,virginica,virginica,virginica,virginica,virginica,virginica,virginica,virginica