# Lab 1 : Data Handling

In [30]:
# ---- Create a new column with a fixed value ----
df['new_col'] = 0 # Adds a column 'new_col' with 0 in every row
print(df)

# ---- Add/merge two numeric columns ----
df['new'] = df['sepal_length'] + df['sepal_width'] # Adds the two columns
print(df)

# ---- Multiply two columns ----
df['new_a'] = df['sepal_length'] * df['sepal_width'] # Multiplies the two columns
print(df)

     sepal_length  sepal_width  petal_length  petal_width    species  new_col  \
0             5.1          3.5           1.4          0.2     setosa        0
1             4.9          3.0           1.4          0.2     setosa        0
2             4.7          3.2           1.3          0.2     setosa        0
3             4.6          3.1           1.5          0.2     setosa        0
4             5.0          3.6           1.4          0.2     setosa        0
..            ...          ...           ...          ...        ...      ...
145           6.7          3.0           5.2          2.3  virginica        0
146           6.3          2.5           5.0          1.9  virginica        0
147           6.5          3.0           5.2          2.0  virginica        0
148           6.2          3.4           5.4          2.3  virginica        0
149           5.9          3.0           5.1          1.8  virginica        0

     new  new_a
0    8.6    8.6
1    7.9    7.9
2    7.9    7.9
3    7.7    7.7
4    8.6    8.6
..   ...    ...
145  9.7    9.7
146  8.8    8.8
147  9.5    9.5
148  9.6    9.6
149  8.9    8.9

[150 rows x 8 columns]
     sepal_length  sepal_width  petal_length  petal_width    species  new_col  \
0             5.1          3.5           1.4          0.2     setosa        0
1             4.9          3.0           1.4          0.2     setosa        0
2             4.7          3.2           1.3          0.2     setosa        0
3             4.6          3.1           1.5          0.2     setosa        0
4             5.0          3.6           1.4          0.2     setosa        0
..            ...          ...           ...          ...        ...      ...
145           6.7          3.0           5.2          2.3  virginica        0
146           6.3          2.5           5.0          1.9  virginica        0
147           6.5          3.0           5.2          2.0  virginica        0
148           6.2          3.4           5.4          2.3  virginica        0
149           5.9          3.0           5.1          1.8  virginica        0

     new  new_a
0    8.6    8.6
1    7.9    7.9
2    7.9    7.9
3    7.7    7.7
4    8.6    8.6
..   ...    ...
145  9.7    9.7
146  8.8    8.8
147  9.5    9.5
148  9.6    9.6
149  8.9    8.9

[150 rows x 8 columns]
     sepal_length  sepal_width  petal_length  petal_width    species  new_col  \
0             5.1          3.5           1.4          0.2     setosa        0
1             4.9          3.0           1.4          0.2     setosa        0
2             4.7          3.2           1.3          0.2     setosa        0
3             4.6          3.1           1.5          0.2     setosa        0
4             5.0          3.6           1.4          0.2     setosa        0
..            ...          ...           ...          ...        ...      ...
145           6.7          3.0           5.2          2.3  virginica        0
146           6.3          2.5           5.0          1.9  virginica        0
147           6.5          3.0           5.2          2.0  virginica        0
148           6.2          3.4           5.4          2.3  virginica        0
149           5.9          3.0           5.1          1.8  virginica        0

     new  new_a
0    8.6  17.85
1    7.9  14.70
2    7.9  15.04
3    7.7  14.26
4    8.6  18.00
..   ...    ...
145  9.7  20.10
146  8.8  15.75
147  9.5  19.50
148  9.6  21.08
149  8.9  17.70

[150 rows x 8 columns]

In [32]:
# Data Inspection & Filtering

# ---- Count categories in a column ----
categories = pd.Categorical(df['species'])
print(categories) # Shows unique species: Setosa, Versicolor, Virginica

# ---- Find maximum value in a column ----
max_width = max(df['sepal_width'])
print(max_width)

['setosa', 'setosa', 'setosa', 'setosa', 'setosa', ..., 'virginica', 'virginica', 'virginica', 'virginica', 'virginica']
Length: 150
Categories (3, object): ['setosa', 'versicolor', 'virginica']
4.4

In [92]:
# Filtering by Maximum Value & Setting Index

# ---- Filter rows where column = max value ----
max_width_rows = df[df['sepal_width'] == max(df['sepal_width'])]
print(max_width_rows)

# ---- Set index temporarily ----
temp_index = df.set_index('sepal_width')
print(temp_index) # Only for display, df itself unchanged

# ---- Set index permanently ----
# df.set_index('class', inplace=True) # Uncomment if 'class' column exists

    sepal_length  sepal_width  petal_length  petal_width species  new_col  \
15           5.7          4.4           1.5          0.4  setosa        0

     new  new_a
15  10.1   10.1
             sepal_length  petal_length  petal_width    species  new_col  new  \
sepal_width
3.5                   5.1           1.4          0.2     setosa        0  8.6
3.0                   4.9           1.4          0.2     setosa        0  7.9
3.2                   4.7           1.3          0.2     setosa        0  7.9
3.1                   4.6           1.5          0.2     setosa        0  7.7
3.6                   5.0           1.4          0.2     setosa        0  8.6
...                   ...           ...          ...        ...      ...  ...
3.0                   6.7           5.2          2.3  virginica        0  9.7
2.5                   6.3           5.0          1.9  virginica        0  8.8
3.0                   6.5           5.2          2.0  virginica        0  9.5
3.4                   6.2           5.4          2.3  virginica        0  9.6
3.0                   5.9           5.1          1.8  virginica        0  8.9

             new_a
sepal_width
3.5            8.6
3.0            7.9
3.2            7.9
3.1            7.7
3.6            8.6
...            ...
3.0            9.7
2.5            8.8
3.0            9.5
3.4            9.6
3.0            8.9

[150 rows x 7 columns]

In [33]:
# Reset Index & Drop NA Values

# ---- Reset index ----
df_reset = df.reset_index()
print(df_reset)

# ---- Drop rows with NA values temporarily ----
df_drop_temp = df.dropna()
print(df_drop_temp)

# ---- Drop rows permanently ----
# df.dropna(inplace=True)

# ---- Drop columns with NA values ----
# df.dropna(axis=1, inplace=True)

     index  sepal_length  sepal_width  petal_length  petal_width    species  \
0        0           5.1          3.5           1.4          0.2     setosa
1        1           4.9          3.0           1.4          0.2     setosa
2        2           4.7          3.2           1.3          0.2     setosa
3        3           4.6          3.1           1.5          0.2     setosa
4        4           5.0          3.6           1.4          0.2     setosa
..     ...           ...          ...           ...          ...        ...
145    145           6.7          3.0           5.2          2.3  virginica
146    146           6.3          2.5           5.0          1.9  virginica
147    147           6.5          3.0           5.2          2.0  virginica
148    148           6.2          3.4           5.4          2.3  virginica
149    149           5.9          3.0           5.1          1.8  virginica

     new_col  new  new_a
0          0  8.6  17.85
1          0  7.9  14.70
2          0  7.9  15.04
3          0  7.7  14.26
4          0  8.6  18.00
..       ...  ...    ...
145        0  9.7  20.10
146        0  8.8  15.75
147        0  9.5  19.50
148        0  9.6  21.08
149        0  8.9  17.70

[150 rows x 9 columns]
     sepal_length  sepal_width  petal_length  petal_width    species  new_col  \
0             5.1          3.5           1.4          0.2     setosa        0
1             4.9          3.0           1.4          0.2     setosa        0
2             4.7          3.2           1.3          0.2     setosa        0
3             4.6          3.1           1.5          0.2     setosa        0
4             5.0          3.6           1.4          0.2     setosa        0
..            ...          ...           ...          ...        ...      ...
145           6.7          3.0           5.2          2.3  virginica        0
146           6.3          2.5           5.0          1.9  virginica        0
147           6.5          3.0           5.2          2.0  virginica        0
148           6.2          3.4           5.4          2.3  virginica        0
149           5.9          3.0           5.1          1.8  virginica        0

     new  new_a
0    8.6  17.85
1    7.9  14.70
2    7.9  15.04
3    7.7  14.26
4    8.6  18.00
..   ...    ...
145  9.7  20.10
146  8.8  15.75
147  9.5  19.50
148  9.6  21.08
149  8.9  17.70

[150 rows x 8 columns]

In [34]:
# Grouping Data

# ---- Group by species ----
g = df.groupby('species')

# ---- Sum per group ----
print(g.sum())

# ---- Mean per group ----
print(g.mean())

# ---- Max per group ----
print(g.max())

            sepal_length  sepal_width  petal_length  petal_width  new_col  \
species
setosa             250.3        170.9          73.2         12.2        0
versicolor         296.8        138.5         213.0         66.3        0
virginica          329.4        148.7         277.6        101.3        0

              new   new_a
species
setosa      421.2  860.44
versicolor  435.3  826.31
virginica   478.1  984.23
            sepal_length  sepal_width  petal_length  petal_width  new_col  \
species
setosa             5.006        3.418         1.464        0.244        0
versicolor         5.936        2.770         4.260        1.326        0
virginica          6.588        2.974         5.552        2.026        0

              new    new_a
species
setosa      8.424  17.2088
versicolor  8.706  16.5262
virginica   9.562  19.6846
            sepal_length  sepal_width  petal_length  petal_width  new_col  \
species
setosa               5.8          4.4           1.9          0.6        0
versicolor           7.0          3.4           5.1          1.8        0
virginica            7.9          3.8           6.9          2.5        0

             new  new_a
species
setosa      10.1  25.08
versicolor  10.2  22.40
virginica   11.7  30.02

### Convert a Column (USD -> SAR example)

In [95]:
#Using Titanic dataset 
df=pd.read_csv('titanic.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [96]:
#Using function
def f(n):
    return n*5.5
df['u_fare']=df['Fare'].apply(f)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,u_fare
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,39.87500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,392.05815
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,43.58750
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,292.05000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,44.27500
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,71.50000
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,165.00000
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,128.97500
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,165.00000
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,42.62500

In [97]:
#Uisng Lambda
df['u_fare']=df['Fare'].apply(lambda x: x*5.5)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,u_fare
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,39.87500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,392.05815
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,43.58750
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,292.05000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,44.27500
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,71.50000
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,165.00000
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,128.97500
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,165.00000
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,42.62500

In [98]:
#Create DataFrame from Dictionary
data={
    'a':[2,4,5,6],
    'b':[12,343,54,56],
    'c':['Manab','Soubhik','Avick','Jon']
}

In [99]:
import pandas as pd
df=pd.DataFrame(data)
df

   a    b        c
0  2   12    Manab
1  4  343  Soubhik
2  5   54    Avick
3  6   56      Jon

In [100]:
df.set_index("a",inplace =True)
df

     b        c
a
2   12    Manab
4  343  Soubhik
5   54    Avick
6   56      Jon

In [122]:
#Reset Index & Reindex
df.reset_index()
df1=pd.DataFrame(data,index=['a','b','c','d'])
#Re-arrange the index of my data frame
df1.reindex(['b','c','a','d'])
df1

   a    b        c
a  2   12    Manab
b  4  343  Soubhik
c  5   54    Avick
d  6   56      Jon

In [102]:
#Applying function to a DataFrame
def test(x):
    return x.sum()
df1.apply(test) #column wise sum, axis=0 by default

a                      17
b                     465
c    ManabSoubhikAvickJon
dtype: object

In [103]:
# Using Lambda
df1.apply(lambda x: x.sum())

a                      17
b                     465
c    ManabSoubhikAvickJon
dtype: object

In [124]:
# Applying to Specific Columns
df2=df1[['a','b']]
df2
df2.apply(lambda x:x**2)
# df1.apply(lambda x:x**2) # Give error

    a       b
a   4     144
b  16  117649
c  25    2916
d  36    3136

In [127]:
#Sorting
df1.sort_values('c') #Sort by column C
df1.sort_index(ascending=False) # Sort by index

   a    b        c
d  6   56      Jon
c  5   54    Avick
b  4  343  Soubhik
a  2   12    Manab

In [130]:
#Working with Text Columns
df3=pd.DataFrame({
    'desc':['Data Science Masters course is highly curated and uniquely designed according to the latest industry standards. This program instills students the skills essential to knowledge discovery efforts to identify standard, novel, and truly differentiated solutions and decision-making, including skills in managing, querying, analyzing, visualizing, and extracting meaning from extremely large data sets. This trending program provides students with the statistical, mathematical and computational skills needed to meet the large-scale data science challenges of todays professional world. You will learn all the stack required to work in data science industry including cloud infrastructure and real-time industry projects. This course will be taught in Hindi language.']
})

In [134]:
#Show long text properly
pd.set_option('display.max_colwidth',1000)
df3

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           desc
0  Data Science Masters course is highly curated and uniquely designed according to the latest industry standards. This program instills students the skills essential to knowledge discovery efforts to identify standard, novel, and truly differentiated solutions and decision-making, including skills in managing, querying, analyzing, visualizing, and extracting meaning from extremely large data sets. This trending program provides students with the statistical, mathematical and computational skills needed to meet the large-scale data science challenges of todays professional world. You will learn all the stack required to work in data science industry including cloud infrastructure and real-time industry projects. This course will be taught in Hindi language.

In [110]:
df4=pd.DataFrame({
    'desc':['Data Science Masters course is highly curated and uniquely designed according to the latest industry standards. This program instills students the skills essential to knowledge discovery efforts to identify standard, novel, and truly differentiated solutions and decision-making, including skills in managing, querying, analyzing, visualizing, and extracting meaning from extremely large data sets. This trending program provides students with the statistical, mathematical and computational skills needed to meet the large-scale data science challenges of todays professional world', 'You will learn all the stack required to work in data science industry including cloud infrastructure and real-time industry projects. This course will be taught in Hindi language.', 'My name is Manab']
})

In [135]:
#Length of text
df4['Length']=df4['desc'].apply(len)

#Word Count:
df4['word_count']=df4['desc'].apply(lambda x:len(x.split()))

#Summary Statistics
df4['Length'].mean()
df4['Length'].std()
df4['Length'].sum()

np.int64(778)